# -*- coding: utf-8 -*-
"""CORRELACION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzHxG0onWWbVFs3euwZ0qnsitp1jM4qG
"""

pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("FARMACIA").getOrCreate()



data_var = [(4,4),(4,3),(5,4),(4,3),(3,2),(3,3),(3,4),(4,3),(5,4),(4,3),(3,3),(2,2),(2,3),(2,4),(3,4)]
columns_var = ["Servicio", "Ubicacion"]
variable_corr = spark.createDataFrame(data_var, columns_var)

correlacion = variable_corr.select(corr(col("Servicio"),col("Ubicacion")).alias("correlacion")).collect()[0]["correlacion"]

print("la correlacion es:",correlacion)