# -*- coding: utf-8 -*-
"""MEDIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzHxG0onWWbVFs3euwZ0qnsitp1jM4qG
"""

pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("FARMACIA").getOrCreate()

spark



data= [("Lima",4),("Callao",2), ("Ayacucho",4),("Huanuco ",3), ("Puno",1),("Loreto",3), ("Libertad",4),("ICA ",3),]
colums = ["Region","sedes"]
variable = spark.createDataFrame(data=data,schema=colums)

variable.select(mean(col("sedes")).alias("media")).show()

variable.select(mean(col("sedes")).alias("media")).collect()[0]["media"]