# -*- coding: utf-8 -*-
"""MODA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzHxG0onWWbVFs3euwZ0qnsitp1jM4qG
"""

pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("FARMACIA").getOrCreate()



data= [("Lima",4),("Callao",2), ("Ayacucho",4),("Huanuco ",3), ("Puno",1),("Loreto",3), ("Libertad",4),("ICA ",3),]
colums = ["Region","sedes"]
variable = spark.createDataFrame(data=data,schema=colums)

var_moda = variable.groupBy("sedes").count().orderBy(col("count").desc()).first()

print("La moda es:",var_moda["sedes"])